name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-unit-test:
    name: Unit Test
    runs-on: macos-15
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Run SourcePackagesParserTests
        run: |
          xcodebuild test \
            -project Examples/Examples.xcodeproj \
            -scheme SourcePackagesParserTests \
            -only-testing:SourcePackagesParserTests \
            -destination "platform=macOS,arch=arm64" \
            -resultBundlePath TestResults/result_bundle | \
            xcbeautify && exit ${PIPESTATUS[0]}
